apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
  labels:
    app: time
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name: nginx
          image: icr.io/nalayathiran-project/time
          ports:
            - containerPort: 5000
