apiVersion: v1
kind: Service
metadata:
  name: nest-sample-service
spec:
  selector:
    app: nest-sample
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
